### PR TITLE
Update main.c

### PR DESCRIPTION
**Pull request by mileticveljko**
I tried code on raspberry Pi 3 and it throws seg fault when framebuffer is initially populated. This way it works fine.
Thank you!

### CODE REVIEW

**Comment by damdoy** [comment]
You are right, there is no need to fill the full screen with a color pattern, it makes more sense like this, i tested it and it works well.

Thanks!

**Comment by mileticveljko** [comment]
Thank you for your repo, btw! It helped a lot!

**Comment by mileticveljko** [comment]
Hey friend. You are measuring time to draw frame buffer. I wanted to measure time to take a frame, deleted frame drawing and put clock taking code at the beginning and at the end of the scope and got different values: 0.0016 - 0.0035. I fully understood your approach, time I measured is the time to dequeue frame and to calculate time for frame taking I need to add it to wanted frame taking period (1/FPS). I basically calculated latency of frame taking and I think it is awesome result. Good job! I am trying to find fastest way to take frame from camera and yours seams to be fastest so far.

What do you think about my way to calculate latency? Do you think it is correct way? Since I have time consuming printf after that semaphore is already freed and there is frame in the queue when I take start value of time. For next step I will put time values in some buffer and print it after 100 frames. Do you maybe have even better idea to measure time.

**Comment by mileticveljko** [comment]
I tested it in the way where I am packing time stamp values in buffer and print it after and results are 0.0033 - 0.0036 s. 
Here is the code of frame taking:
` for(int i = 0; i<100; i++) {

    t = clock();

    sem_wait(&semaphore);

    buffer = mmal_queue_get(pool->queue);

    mmal_port_send_buffer(video_port, buffer);

    t = clock() - t;
    time_taken[i] = ((double)t)/CLOCKS_PER_SEC;`

**Pull request merged**
